# Generated by Django 4.1.4 on 2023-04-13 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_sign_in_alter_travel_travel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='price',
            field=models.IntegerField(default=15000, null=True, verbose_name='總價'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='travel_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 13, 16, 13, 34, 93532, tzinfo=datetime.timezone.utc), max_length=20, verbose_name='旅程時間'),
        ),
    ]
