# Generated by Django 4.1.4 on 2023-04-13 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_travel_travel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='travel_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 13, 15, 50, 44, 227810, tzinfo=datetime.timezone.utc), max_length=20, verbose_name='旅程時間'),
        ),
    ]
