# Generated by Django 4.1.4 on 2023-04-13 15:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_travel_total_number_alter_travel_travel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakfast',
            name='booking_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.travel'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='travel',
            name='travel_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 13, 15, 57, 29, 125109, tzinfo=datetime.timezone.utc), max_length=20, verbose_name='旅程時間'),
        ),
    ]
