# Generated by Django 4.2 on 2023-04-15 07:45

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='breakfast_shop',
            fields=[
                ('breakfast_items', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='早餐品項')),
                ('breakfast_name', models.CharField(max_length=10, verbose_name='早餐名稱')),
                ('breakfast_choices', models.CharField(choices=[('小吃', '小吃'), ('麵飯', '麵飯'), ('湯', '湯')], default='', max_length=5, verbose_name='類別')),
                ('breakfast_price', models.CharField(max_length=10, verbose_name='早餐價格')),
                ('breakfast_status', models.CharField(choices=[('停止銷售', '停止銷售'), ('銷售中', '銷售中')], default='', max_length=4, verbose_name='餐點狀態')),
            ],
        ),
        migrations.CreateModel(
            name='dinner_shop',
            fields=[
                ('dinner_items', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='晚餐品項')),
                ('dinner_name', models.CharField(max_length=10, verbose_name='晚餐名稱')),
                ('dinner_size', models.CharField(choices=[('大', '大'), ('小', '小')], default='', max_length=4, verbose_name='尺寸')),
                ('dinner_type', models.CharField(choices=[('小吃', '小吃'), ('麵飯', '麵飯'), ('熱炒', '熱炒')], default='', max_length=5, verbose_name='類別')),
                ('dinner_price', models.CharField(max_length=10, verbose_name='晚餐價格')),
                ('dinner_status', models.CharField(choices=[('停止銷售', '停止銷售'), ('銷售中', '銷售中')], default='', max_length=4, verbose_name='餐點狀態')),
            ],
        ),
        migrations.CreateModel(
            name='member',
            fields=[
                ('sign_in_type', models.CharField(max_length=20, verbose_name='類別')),
                ('line_account', models.CharField(max_length=20, null=True, verbose_name='line帳號')),
                ('fb_account', models.CharField(max_length=20, null=True, verbose_name='fb帳號')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('phone', models.CharField(max_length=20, verbose_name='電話')),
                ('Email', models.CharField(default=0, max_length=40, primary_key=True, serialize=False, verbose_name='信箱')),
                ('createdate', models.DateTimeField(default=django.utils.timezone.now, max_length=30, verbose_name='創立日期')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('item_name', models.CharField(max_length=100)),
                ('item_price', models.IntegerField()),
                ('item_quantity', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('order_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='sign_in',
            fields=[
                ('account', models.CharField(default=0, max_length=20, primary_key=True, serialize=False, verbose_name='帳號')),
                ('password', models.CharField(max_length=20, verbose_name='密碼')),
            ],
        ),
        migrations.CreateModel(
            name='travel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_number', models.IntegerField(blank=True, null=True, verbose_name='人數')),
                ('travel_date', models.DateField(default=datetime.datetime(2023, 4, 15, 7, 45, 17, 981926, tzinfo=datetime.timezone.utc), max_length=20, verbose_name='旅程時間')),
                ('food_id', models.CharField(default=0, max_length=10, null=True, verbose_name='飲食訂單編號')),
                ('price', models.IntegerField(default=15000, null=True, verbose_name='總價')),
            ],
        ),
        migrations.CreateModel(
            name='participate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=10, verbose_name='參加人姓名')),
                ('total_number', models.CharField(max_length=5, verbose_name='參加總人數')),
                ('MID', models.CharField(max_length=10, verbose_name='身分證字號')),
                ('birthday', models.DateField(max_length=20, verbose_name='出生年月日')),
                ('insurance_status', models.CharField(choices=[('未投保', '未投保'), ('已投保', '已投保')], default='', max_length=5, verbose_name='保險狀態')),
                ('booking_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.travel')),
            ],
        ),
        migrations.CreateModel(
            name='Dinner',
            fields=[
                ('dinner_id', models.CharField(default=1, max_length=20, primary_key=True, serialize=False, verbose_name='晚餐訂單編號')),
                ('dinner_items', models.CharField(max_length=10, verbose_name='晚餐品項')),
                ('quality', models.IntegerField(verbose_name='數量')),
                ('price', models.IntegerField(verbose_name='售價')),
                ('booking_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.travel')),
            ],
        ),
        migrations.CreateModel(
            name='breakfast',
            fields=[
                ('breakfast_id', models.CharField(default=1, max_length=10, primary_key=True, serialize=False, verbose_name='早餐訂單編號')),
                ('breakfast_items', models.CharField(max_length=10, verbose_name='早餐品項')),
                ('quality', models.IntegerField(verbose_name='數量')),
                ('price', models.IntegerField(verbose_name='售價')),
                ('booking_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.travel')),
            ],
        ),
    ]
