# Generated by Django 4.2 on 2023-04-15 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='travel_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 15, 8, 2, 34, 480354, tzinfo=datetime.timezone.utc), max_length=20, verbose_name='旅程時間'),
        ),
    ]
