# Generated by Django 4.1.4 on 2023-04-13 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_remove_travel_total_number_alter_travel_travel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='total_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='人數'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='travel_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 13, 15, 51, 29, 29754, tzinfo=datetime.timezone.utc), max_length=20, verbose_name='旅程時間'),
        ),
    ]
