# Generated by Django 4.1.5 on 2023-04-15 03:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0012_member_id_alter_member_name_alter_sign_in_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="travel",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="travel",
            name="travel_date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 4, 15, 3, 12, 48, 87309, tzinfo=datetime.timezone.utc
                ),
                max_length=20,
                verbose_name="旅程時間",
            ),
        ),
    ]
