# Generated by Django 4.1.5 on 2023-04-15 06:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0013_alter_travel_id_alter_travel_travel_date"),
    ]

    operations = [
        migrations.RemoveField(model_name="member", name="id",),
        migrations.RemoveField(model_name="sign_in", name="id",),
        migrations.AlterField(
            model_name="member",
            name="Email",
            field=models.CharField(
                default=0,
                max_length=40,
                primary_key=True,
                serialize=False,
                verbose_name="信箱",
            ),
        ),
        migrations.AlterField(
            model_name="sign_in",
            name="account",
            field=models.CharField(
                max_length=20, primary_key=True, serialize=False, verbose_name="帳號"
            ),
        ),
        migrations.AlterField(
            model_name="travel",
            name="travel_date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 4, 15, 6, 44, 1, 66713, tzinfo=datetime.timezone.utc
                ),
                max_length=20,
                verbose_name="旅程時間",
            ),
        ),
    ]
