# Generated by Django 4.2 on 2023-04-15 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_alter_member_email_alter_travel_travel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='travel_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 15, 7, 24, 59, 843948, tzinfo=datetime.timezone.utc), max_length=20, verbose_name='旅程時間'),
        ),
    ]
